version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-2)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t 124121153800.dkr.ecr.ap-northeast-2.amazonaws.com/team1-ecr:latest .
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 124121153800.dkr.ecr.ap-northeast-2.amazonaws.com/team1-ecr:latest
  post_build:
    commands:
      - echo Build completed on `date`
