service: consumer

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  vpc:
    securityGroupIds:
      - sg-0dbdd2082538975ba
    subnetIds:
      - subnet-093bc1cebb91c00f9
      - subnet-001d2da3df3529a3f
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource: 'arn:aws:sqs:ap-northeast-2:124121153800:SQS-hwani'


functions:
  myFunction:
    handler: handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:ap-northeast-2:124121153800:SQS-hwani
