global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend-service'
    static_configs:
      - targets: ['10.0.148.73:3000', 'team1-api-alb-1928618655.ap-northeast-2.elb.amazonaws.com']

rule_files:
  - "rule.yml"
