version: '3'
services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:prometheus-${{ env.IMAGE_TAG }}

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:grafana-${{ env.IMAGE_TAG }}
