version: '3'
services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    image: ${AWS_REGISTRY_URL}/${ECR_REPOSITORY}:prometheus-${IMAGE_TAG}

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    image: ${AWS_REGISTRY_URL}/${ECR_REPOSITORY}:grafana-${IMAGE_TAG}
