version: '3'
services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    image: ${AWS_REGISTRY_URL}/${ECR_REPOSITORY}:prometheus-${IMAGE_TAG}
  
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    image: ${AWS_REGISTRY_URL}/${ECR_REPOSITORY}:grafana-${IMAGE_TAG}
