service: lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2
  iam:
    role: 
      statements:
        - Effect: Allow
          Action: 
            - sqs:SendMessage
            - ec2:RunInstances
            - rds-db:connect
          Resource: '*'

constructs:
  jobs:
    type: queue
    worker:
      handler: index.consumer

        
functions:
  producer:
    handler: index.producer
    events:
      - schedule: rate(1 minute)
    environment:
      QUEUE_URL: ${constructs.jobs.queueUrl}


plugins:
  - serverless-lift
