name: Deploy to ECR

on:
  push:
    branches:
      - main
env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: monitoring-ecr
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Compose
      run: |
        echo "AWS_REGISTRY_URL=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

    - name: Build, tag, and push Prometheus and Grafana images to Amazon ECR
      run: |
        cd monitoring
        docker-compose build
        docker-compose push
